// The OpenNext worker is generated by `npm run build:worker`.
// @ts-expect-error generated module is not present before the first build
import handler from "./.open-next/worker.js";

export { CompanyUpdateWorkflow } from "./src/server/workflows/company-update-workflow";

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
